var getDropDowns = function () {
            return [
                { "Id": "1", "Area": "3rd Party", "Section": "Integration", "Page": "Dealer Track Intergrations" },
                { "Id": "2", "Area": "3rd Party", "Section": "Integration", "Page": "Route 1 Intergrations" },
                { "Id": "3", "Area": "3rd Party", "Section": "Integration", "Page": "Dealer Track Canada Integrations" },
                { "Id": "4", "Area": "3rd Party", "Section": "Integration", "Page": "IDA" },
                { "Id": "5", "Area": "3rd Party", "Section": "Integration", "Page": "ACH" },
                { "Id": "6", "Area": "3rd Party", "Section": "Integration", "Page": "Bureau (EX, EQ, Trans, EX DMS, EQ DMS and Trans DMS)" },
                { "Id": "7", "Area": "3rd Party", "Section": "Integration", "Page": "Lexus Nexis" },
                { "Id": "8", "Area": "Configuration", "Section": "Configuration", "Page": "Dropdown Selections" },
                { "Id": "9", "Area": "Configuration", "Section": "Configuration", "Page": "Create Custom Fields" },
                { "Id": "10", "Area": "Configuration", "Section": "General", "Page": "Publish Rules" },
                { "Id": "11", "Area": "Configuration", "Section": "Applications", "Page": "Duplicate Applications" },
                { "Id": "12", "Area": "Configuration", "Section": "Tables", "Page": "Formulas" },
                { "Id": "13", "Area": "Configuration", "Section": "Notifications", "Page": "Notification Templates" },
                { "Id": "14", "Area": "Configuration", "Section": "Notifications", "Page": "Notification Templates Selection" },
                { "Id": "15", "Area": "Configuration", "Section": "Verifications", "Page": "Funding Rules" },
                { "Id": "16", "Area": "Configuration", "Section": "Verifications", "Page": "Funding Tolorance Rules" },
                { "Id": "17", "Area": "Configuration", "Section": "Verifications", "Page": "Underwriter Stipulations to Documents" },
                { "Id": "18", "Area": "Configuration", "Section": "Risk Setup", "Page": "Usury" },
                { "Id": "19", "Area": "Configuration", "Section": "Risk Setup", "Page": "Payment Call Configuration" },
                { "Id": "20", "Area": "Configuration", "Section": "Risk Setup", "Page": "Scorecard" },
                { "Id": "21", "Area": "Configuration", "Section": "Risk Setup", "Page": "Scorecard Selection" },
                { "Id": "22", "Area": "Configuration", "Section": "Risk Setup", "Page": "Tiers" },
                { "Id": "23", "Area": "Configuration", "Section": "Risk Setup", "Page": "Tier Selection" },
                { "Id": "24", "Area": "Configuration", "Section": "Risk Setup", "Page": "Post-Bureau Rules" },
                { "Id": "25", "Area": "Configuration", "Section": "Risk Setup", "Page": "Credit Policy Setup" },
                { "Id": "26", "Area": "Configuration", "Section": "Risk Setup", "Page": "Vendor Integration Rules" },
                { "Id": "27", "Area": "Configuration", "Section": "Risk Setup", "Page": "Conditional Approval Rules" },
                { "Id": "28", "Area": "Configuration", "Section": "Structure", "Page": "Discount Matrices" },
                { "Id": "29", "Area": "Configuration", "Section": "Structure", "Page": "Discount Matrix Selection" },
                { "Id": "30", "Area": "Configuration", "Section": "Structure", "Page": "Participation Matrix Selection" },
                { "Id": "31", "Area": "Configuration", "Section": "Structure", "Page": "Pricing Matrix Selection" },
                { "Id": "32", "Area": "Configuration", "Section": "Structure", "Page": "Dedup Expenses App vs. Bureau" },
                { "Id": "33", "Area": "Configuration", "Section": "Structure", "Page": "Tradeline Rules" },
                { "Id": "34", "Area": "Configuration", "Section": "Structure", "Page": "Dedup Expenses App vs. Coapp" },
                { "Id": "35", "Area": "Configuration", "Section": "Decisions", "Page": "Auto Decline" },
                { "Id": "36", "Area": "Configuration", "Section": "Decisions", "Page": "Pre-Bureau Rules" },
                { "Id": "37", "Area": "Configuration", "Section": "Page Configurations", "Page": "Decision" },
                { "Id": "38", "Area": "Configuration", "Section": "Page Configurations", "Page": "Verifications" },
                { "Id": "39", "Area": "Configuration", "Section": "Page Configurations", "Page": "Application" },
                { "Id": "40", "Area": "Configuration", "Section": "Applications", "Page": "Existing Customer Rules" },
                { "Id": "41", "Area": "Configuration", "Section": "Security", "Page": "User Admin" },
                { "Id": "42", "Area": "Configuration", "Section": "Security", "Page": "Role Admin" },
                { "Id": "43", "Area": "Configuration", "Section": "Configuration", "Page": "Page Field Selections" },
                { "Id": "44", "Area": "Configuration", "Section": "Configuration", "Page": "Client Defined Dropdowns" },
                { "Id": "45", "Area": "Configuration", "Section": "Third Party", "Page": "Inbound Data Sources" },
                { "Id": "46", "Area": "Configuration", "Section": "Third Party", "Page": "Vendor Integrations" },
                { "Id": "47", "Area": "Configuration", "Section": "Third Party", "Page": "Outbound Data Sources" },
                { "Id": "48", "Area": "Configuration", "Section": "Dealers", "Page": "Dealers" },
                { "Id": "49", "Area": "Configuration", "Section": "Dealers", "Page": "Dealer Groups" },
                { "Id": "50", "Area": "Configuration", "Section": "Dealers", "Page": "Dealer Notes" },
                { "Id": "51", "Area": "Configuration", "Section": "Applications", "Page": "Application Expiration" },
                { "Id": "52", "Area": "Configuration", "Section": "Applications", "Page": "Default Start Page" },
                { "Id": "53", "Area": "Configuration", "Section": "Tables", "Page": "Adverse Action Reasons" },
                { "Id": "54", "Area": "Configuration", "Section": "Tables", "Page": "Documents" },
                { "Id": "55", "Area": "Configuration", "Section": "Tables", "Page": "Questions" },
                { "Id": "56", "Area": "Configuration", "Section": "Tables", "Page": "Return Reasons" },
                { "Id": "57", "Area": "Configuration", "Section": "Tables", "Page": "Statuses" },
                { "Id": "58", "Area": "Configuration", "Section": "Tables", "Page": "Stipulations" },
                { "Id": "59", "Area": "Configuration", "Section": "Tables", "Page": "Stipulation Selection" },
                { "Id": "60", "Area": "Configuration", "Section": "Tables", "Page": "Underwriter Notes" },
                { "Id": "61", "Area": "Configuration", "Section": "Tables", "Page": "Underwriter Notes Selection" },
                { "Id": "62", "Area": "Configuration", "Section": "Verifications", "Page": "Documents to Questions" },
                { "Id": "63", "Area": "Configuration", "Section": "Verifications", "Page": "VF Stipulations to Questions" },
                { "Id": "64", "Area": "Configuration", "Section": "Verifications", "Page": "Disbursement" },
                { "Id": "65", "Area": "Configuration", "Section": "Structure", "Page": "Down Payment Adjustment" },
                { "Id": "66", "Area": "Configuration", "Section": "Structure", "Page": "Excluded Income" },
                { "Id": "67", "Area": "Configuration", "Section": "Structure", "Page": "Housing Status Adjustment" },
                { "Id": "68", "Area": "Configuration", "Section": "Structure", "Page": "Participation Matrices" },
                { "Id": "69", "Area": "Configuration", "Section": "Structure", "Page": "Participation Matrix Selection" },
                { "Id": "70", "Area": "Configuration", "Section": "Dealers", "Page": "Dealer Notes Selection" },
                { "Id": "71", "Area": "Configuration", "Section": "Third Party", "Page": "Credit Bureau Credentials" },
                { "Id": "72", "Area": "Configuration", "Section": "Third Party", "Page": "Boarding File Sources" },
                { "Id": "73", "Area": "Configuration", "Section": "Third Party", "Page": "XML Export Config" },
                { "Id": "74", "Area": "Configuration", "Section": "Third Party", "Page": "Re-export XML" },
                { "Id": "75", "Area": "Configuration", "Section": "Queues", "Page": "Funder Main Queue" },
                { "Id": "76", "Area": "Configuration", "Section": "Queues", "Page": "Funder Queue Status Filter" },
                { "Id": "77", "Area": "Configuration", "Section": "Queues", "Page": "Queue View" },
                { "Id": "78", "Area": "Configuration", "Section": "Queues", "Page": "Underwriter Main Queue" },
                { "Id": "79", "Area": "Configuration", "Section": "Queues", "Page": "Underwriter Queue Status Filter" },
                { "Id": "80", "Area": "Configuration", "Section": "Applications", "Page": "Auto Assign Users" },
                { "Id": "81", "Area": "Configuration", "Section": "Risk Setup", "Page": "Credit Bureau Zip Preferences" },
                { "Id": "82", "Area": "Configuration", "Section": "Risk Setup", "Page": "Multi Decisioning" },
                { "Id": "83", "Area": "Configuration", "Section": "Risk Setup", "Page": "Multi Decision Selection" },
                { "Id": "84", "Area": "Configuration", "Section": "Page Configurations", "Page": "Decision-Lease" },
                { "Id": "85", "Area": "Configuration", "Section": "Page Configurations", "Page": "Dealer App Page" },
                { "Id": "86", "Area": "Configuration", "Section": "Page Configurations", "Page": "Business App Page" },
                { "Id": "87", "Area": "Configuration", "Section": "Lease", "Page": "Base Money Factor Matrices" },
                { "Id": "88", "Area": "Configuration", "Section": "Lease", "Page": "Base Money Factor Matrices Selection" },
                { "Id": "89", "Area": "Configuration", "Section": "Lease", "Page": "Money Factor Setup" },
                { "Id": "90", "Area": "Configuration", "Section": "Queues", "Page": "Personal" },
                { "Id": "91", "Area": "Configuration", "Section": "Queues", "Page": "Manual App" },
                { "Id": "92", "Area": "Configuration", "Section": "Queues", "Page": "Follow Up" },
                { "Id": "93", "Area": "Configuration", "Section": "Leasing Workflow", "Page": "Leasing Workflow" },
                { "Id": "94", "Area": "Configuration", "Section": "Configuration", "Page": "Element Format Rules" },
                { "Id": "95", "Area": "Configuration", "Section": "Third Party", "Page": "Application Sources" },
                { "Id": "96", "Area": "Configuration", "Section": "Third Party", "Page": "Bookout Sources" },
                { "Id": "97", "Area": "Configuration", "Section": "Applications", "Page": "Summary Info" },
                { "Id": "98", "Area": "Configuration", "Section": "Applications", "Page": "Summary Info – Decision Summary" },
                { "Id": "99", "Area": "Configuration", "Section": "Applications", "Page": "Summary Info – Verifications" },
                { "Id": "100", "Area": "Configuration", "Section": "Verifications", "Page": "Upload Center" },
                { "Id": "101", "Area": "Configuration", "Section": "Risk Setup", "Page": "Fraud" },
                { "Id": "102", "Area": "Configuration", "Section": "Decisions", "Page": "Auto Approval" },
                { "Id": "103", "Area": "Configuration", "Section": "Reporting", "Page": "Jericho" },
                { "Id": "104", "Area": "Configuration", "Section": "Security", "Page": "Permission Admin" },
                { "Id": "105", "Area": "Configuration", "Section": "Configuration", "Page": "Force Note Rules" },
                { "Id": "106", "Area": "Configuration", "Section": "General", "Page": "Company Info" },
                { "Id": "107", "Area": "Configuration", "Section": "General", "Page": "Login Screen" },
                { "Id": "108", "Area": "Configuration", "Section": "General", "Page": "Password Rules" },
                { "Id": "109", "Area": "Configuration", "Section": "Queues", "Page": "Manual App Entry Queue" },
                { "Id": "110", "Area": "Configuration", "Section": "Reporting", "Page": "Audit History" },
                { "Id": "111", "Area": "Funding", "Section": "Verifications", "Page": "RIC" },
                { "Id": "112", "Area": "Funding", "Section": "Verifications", "Page": "UW Stips" },
                { "Id": "113", "Area": "Funding", "Section": "Verifications", "Page": "Manual Stips" },
                { "Id": "114", "Area": "Funding", "Section": "Verifications", "Page": "VF Stips" },
                { "Id": "115", "Area": "Funding", "Section": "Verifications", "Page": "Review Stips" },
                { "Id": "116", "Area": "Funding", "Section": "Verifications", "Page": "VF Rules Summary" },
                { "Id": "117", "Area": "Funding", "Section": "Verifications", "Page": "Disbursement" },
                { "Id": "118", "Area": "Funding", "Section": "Verifications", "Page": "Update" },
                { "Id": "119", "Area": "Funding", "Section": "Verifications", "Page": "Custom Tabs" },
                { "Id": "120", "Area": "Manual", "Section": "App Entry", "Page": "Manual App Entry" },
                { "Id": "121", "Area": "Queues", "Section": "Queues", "Page": "Custom" },
                { "Id": "122", "Area": "Queues", "Section": "Queues", "Page": "Underwriter" },
                { "Id": "123", "Area": "Queues", "Section": "Queues", "Page": "Funder" },
                { "Id": "124", "Area": "Reports", "Section": "Reporting", "Page": "Basic Reports" },
                { "Id": "125", "Area": "Reports", "Section": "Reporting", "Page": "Batch Files" },
                { "Id": "126", "Area": "Underwriting", "Section": "Application", "Page": "Application Info Page" },
                { "Id": "127", "Area": "Underwriting", "Section": "Application", "Page": "Decision Page" },
                { "Id": "128", "Area": "Underwriting", "Section": "Application", "Page": "Expenses" },
                { "Id": "129", "Area": "Underwriting", "Section": "Application", "Page": "Bureau" },
                { "Id": "130", "Area": "Underwriting", "Section": "Application", "Page": "Bookout" },
                { "Id": "131", "Area": "Underwriting", "Section": "Application", "Page": "Notifications" },
                { "Id": "132", "Area": "Underwriting", "Section": "Application", "Page": "Create Contract" },
                { "Id": "133", "Area": "Underwriting", "Section": "Application", "Page": "Audit History" },
                { "Id": "134", "Area": "Underwriting", "Section": "Application", "Page": "Rule Summary" },
                { "Id": "135", "Area": "Underwriting", "Section": "Application", "Page": "Download XML" },
                { "Id": "136", "Area": "Underwriting", "Section": "Application", "Page": "Comments History" },
                { "Id": "137", "Area": "Underwriting", "Section": "Application", "Page": "Decision History" },
                { "Id": "138", "Area": "Underwriting", "Section": "Application", "Page": "Errors" },
                { "Id": "139", "Area": "Wizard", "Section": "Wizard", "Page": "Wizard" },
                { "Id": "140", "Area": "Workflows", "Section": "Underwriting Workflow", "Page": "Underwriting Workflow" },
                { "Id": "141", "Area": "Workflows", "Section": "Funder Workflow", "Page": "Funder Workflow" },
                { "Id": "142", "Area": "Workflows", "Section": "New App Workflow (DT)", "Page": "New App Workflow (DT)" },
                { "Id": "143", "Area": "Workflows", "Section": "New App Workflow (R1)", "Page": "New App Workflow (R1)" },
                { "Id": "144", "Area": "Workflows", "Section": "New App Workflow (MAN)", "Page": "New App Workflow (MAN)" },
                { "Id": "145", "Area": "Workflows", "Section": "Payment Call Workflow", "Page": "Payment Call Workflow" }
            ];
        };